### ISSUE TITLE
S1 | Mock Users API

### ISSUE THREAD

**Issue by raghunat** [raghunat/scavenger-hunt#15]
# Story
- As a project
- I would like to mock the users api
- So that I can have a base API to test against

# Acceptance Criteria
- An /users api that accepts a GET request and returns a list of users

# Approach
- This route should be in a file like  `users-api/routes/users.js`
- This file would be required by `users-api/app.js` to expose the route

**Comment by raghunat** [comment]
@shalayiding @esayers85

**Comment by raghunat** [comment]
@kell3991 @khan7866 @Anthony Shibitov

**Comment by anthonyshibitov** [comment]
https://github.com/anthonyshibitov 

i think i renamed my account and thats why its not showing up

**Comment by kell3991** [comment]
In what format should the user list by returned (i.e. json)?

**Comment by raghunat** [comment]
@kell3991 Yes. something along the lines of `res.json({id:1, name:'patrick'})` for an example
