### ISSUE TITLE
S2 | Set up a Mongo Hosting

### ISSUE THREAD

**Issue by raghunat** [raghunat/scavenger-hunt#33]
# Data Store
## Story
- As a developer
- I need a scalable datastore for storing users and spots

## Acceptance Criteria
- Create a "scavanger-hunt" gmail account **(do not embed the password anywhere in code!)**
- Follow http://learnwebtutorials.com/mongodb-tutorial-getting-started-mongolab with that email account (free tier)
    - The tutorial has you test your new db from the terminal. Please do those steps, and take a screenshot of it, and paste it here
- Paste in a ticket comment listing an object from your terminal
- Email only the professor the credentials for the gmail account, and the mongo lab credentials at this time.

**Comment by raghunat** [comment]
@CalebSarikey

**Comment by raghunat** [comment]
@esayers85

**Comment by CalebSarikey** [comment]
Gmail and Mongo credentials have been emailed to professor.

Attached are screenshots showing terminal sessions of the following (one from Caleb’s machine and one from Eric’s machine):

	-connect to MongoDB scavenger-hunt database

	-display the db name using command “db”

	-display a list of collections within the db using command “show collections”

	-display a list of users using command “show users”

	-display documents within the ‘people’ collection using command “db.people.find()” 

![mongo caleb](https://user-images.githubusercontent.com/36275679/37909118-0d1f6a8a-30d8-11e8-9e73-076b710cd11b.png)
![mongo eric](https://user-images.githubusercontent.com/36275679/37909119-0d2e6954-30d8-11e8-8ed3-5d6ef2bbdf92.PNG)

**Comment by raghunat** [comment]
Nice work
