### ISSUE TITLE
S3 | Create a Base Image Queue API

### ISSUE THREAD

**Issue by raghunat** [raghunat/scavenger-hunt#48]
## Story
- As a developer
- I need a bootstrapped Image Queue API
- So that I can start writing the next API for our application

## Acceptance Criteria
- An image-api folder
- A basic npm package.json with express, mongodb, mocha, should, and body-parser installed
- A basic app.js file like the other APIs
- A db/index.js like the other APIs
- an alive route like the other APIs

**Comment by raghunat** [comment]
@mclark1996

**Comment by mclark1996** [comment]
S3 #48
