### ISSUE TITLE
S4 | Create a /processes route

### ISSUE THREAD

**Issue by raghunat** [raghunat/scavenger-hunt#69]
# Story
- As an API, I should have a way to see process status
- So that I can debug them

# Acceptance Criteria
- a `image-api/routes/process.js` file that exports an express router
- Has a `/processes` get route that for now, only `res.json([{id: 1, status: 'pending'}])`

**Comment by raghunat** [comment]
@nasklar

**Comment by nasklar** [comment]
#69 done
